image:
  repository: lscr.io/linuxserver/qbittorrent
  pullPolicy: IfNotPresent
  tag: "4.6.5-r0-ls334"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3434

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http