apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Etc/UTC"
          - name: WEBUI_PORT
            value: "3434"
          - name: TORRENTING_PORT
            value: "6881"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /downloads
              name: downloads
            - mountPath: /config
              name: appdata
      volumes:
      - name: downloads
        nfs:
          path: /export/home-lab-nas-runtime/qbittorrent/downloads
          server: 192.168.2.10
      - name: appdata
        nfs:
          path: /export/home-lab-nas-runtime/qbittorrent/appdata
          server: 192.168.2.10