apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Etc/UTC"
          - name: WEBUI_PORT
            value: "3434"
          - name: TORRENTING_PORT
            value: "6881"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3434
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.volumeMounts}}
          volumeMounts:
            {{- toYaml .Values.persistence.volumeMounts | nindent 12 }}
          {{- end}}
      {{- if .Values.persistence.volumes}}
      volumes:
        {{- toYaml .Values.persistence.volumes | nindent 12 }}
      {{- end}}