image:
  repository: linuxserver/qbittorrent 
  pullPolicy: IfNotPresent
  tag: "5.0.0"

namespace:
  name: default

ingress:
  enabled: true
  host: qbittorrent.home-lab.begoodguys.ovh
  tls:
    secretName: qbittorrent-home-lab-ovh-tls-prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    spec.ingressClassName: traefik

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 400m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: / 
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

persistence:
  volumes:
    - name: downloads
      nfs:
        path: /export/home-lab-nas-runtime/qbittorrent/downloads
        server: 192.168.2.10
    - name: appdata
      nfs:
        path: /export/home-lab-nas-runtime/qbittorrent/appdata  
        server: 192.168.2.10
  volumeMounts:
    - mountPath: /downloads
      name: downloads
    - mountPath: /config
      name: appdata